### ISSUE TITLE
Avoid rethrowing exception in functional wrappers

### ISSUE THREAD

**Issue by vbezhenar** [rainerhahnekamp/sneakythrow#3]
Currently `sneaked` functions rethrow exceptions which incurs some performance penalty. It's possible to avoid that with slightly changed signatures of SneakyFunction, etc. Example:

    @FunctionalInterface
    public interface SneakyFunction<T, R, E extends Exception> {
        R apply(T t) throws E;
    }

    public static <T, R, E extends Exception> Function<T, R> sneaked(SneakyFunction<T, R, E> function) {
        return t -> {
            @SuppressWarnings("unchecked") SneakyFunction<T, R, RuntimeException> f1 = (SneakyFunction<T, R, RuntimeException>) function;
            return f1.apply(t);
        };
    }

**Comment by rainerhahnekamp** [comment]
Thanks. I will look into it asap.

**Comment by rainerhahnekamp** [comment]
@vbezhenar Changes have been integrated into version 1.2.0. Thanks for your support.
